### PR TITLE
fix bug with normalization of transitory sensitivities with interfaces

### LINKED ISSUE #223: No sensitivity for interface reactions
This may be user error, or just a fundamental misunderstanding, but when doing transitory sensitivities (trapezoidal and normalized), I find that all of the sensitivities for the interface reactions are 0. I have attached an example using the Gas-Catalyst Interface notebook. 

if you look at the sensitivities returned by `transitorysensitivitiesfulltrapezoidal`, all of the sensitivities for CH4 are either the gas phase or surface phase. there are no adsorption/desorption reactions, no matter what time you choose.

top 20 at t=1e-6s
image

top 20 at t=0.1s
image

but if I specifically look at all of the adsorption/desorption reactions for CH4, the values are all 0. 
image

I thought maybe it was because I was normalizing, but I ran into another issue when I set `normalized=false`. it looks like the `transitorysensitivitiesfulltrapezoidal` function is only set up for the `Simulation` object, and not the `SystemSimulation` object, so I get the error 'type SystemSimulation has no field domain'. 
[Gas-Catalyst Interface.ipynb.zip](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/files/11918431/Gas-Catalyst.Interface.ipynb.zip)

### PR DESCRIPTION
**Pull request by mjohnson541**
Should fix #223

### CODE REVIEW

**Comment by mjohnson541** [comment]
@ChrisBNEU can you test if this solves your problem?

File: src/TransitorySensitivities.jl [hunk 1]
```diff
@@ -205,6 +208,11 @@ function normalizeadjointtransitorysensitivities!(dSdt,ssys::SystemSimulation,t,
             dSdt ./= y[ind]
         end
     end
+    for (i,inter) in enumerate(ssys.interfaces)
+        if isa(inter,AbstractReactiveInternalInterface)
```
Comment (hwpang) [inline src/TransitorySensitivities.jl:212]: Can you add blanks after the commas here

File: src/TransitorySensitivities.jl [hunk 2]
```diff
@@ -178,10 +183,8 @@ end
 
 function normalizeparamtransitorysensitivities!(dSdt,ssys::SystemSimulation,t,ind)
     y = ssys.sol(t)
+    dSdt .*= ssys.p[ind]
     for sim in ssys.sims
-        if sim.domain.parameterindexes[1]+length(sim.species) < ind && sim.domain.parameterindexes[2] > ind
-            dSdt .*= ssys.p[ind]
-        end
         @views ns = y[sim.domain.indexes[1]:sim.domain.indexes[2]]
```
Comment (hwpang) [inline src/TransitorySensitivities.jl:188]: Should revert this because we should only apply this correction to rate. The old way of implement will only happen once if the ind is within the particular simulation.

Comment (mjohnson541) [reply src/TransitorySensitivities.jl]: Done

File: src/TransitorySensitivities.jl (hunk 1 above)
Comment (mjohnson541) [reply src/TransitorySensitivities.jl]: added

File: src/TransitorySensitivities.jl [hunk 3]
```diff
@@ -163,6 +163,11 @@ function normalizefulltransitorysensitivities!(dSdt,ssys::SystemSimulation,t)
...
         @views dSdt[sim.domain.indexes[1]:sim.domain.indexes[2],:] ./= ns
     end
+    for (i,inter) in enumerate(ssys.interfaces)
+        if isa(inter,AbstractReactiveInternalInterface)
```
[the remark this answers is not in the document]
Comment (mjohnson541) [reply src/TransitorySensitivities.jl]: added
